# Generated by Django 5.1.7 on 2025-03-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('avatar', models.URLField(max_length=2000)),
            ],
        ),
    ]
